/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp; //bitcamp.myapp 패키지에 속하는 클래스를 정의

public class App { // App이라는 이름의 public 클래스를 선언
    public String getGreeting() { // getGreeting이라는 이름의 public 메서드 선언. 이 메서드는 문자열을 반환 String
        return "Hello World!"; // 메서드의 실행 결과로 Hello world! 출력
    }

    public static void main(String[] args) { // Main이라는 이름의 public static 메서드 선언
                                             // 프로그램의 시작점의 역할. String 배열 타입의 args 매개변수를 받음
        System.out.println(new App().getGreeting()); // App 클래스의 인스턴스를 생성하고 getGreeting 메서드를 호출하여 반환된 문자열 출력
    }
}
